modelproject/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:id>', detail, name='detail'),
    path('new/', new_with_django_form, name='new'),
    path('create/', create_with_django_form, name='create'),
    path("update/<int:id>", update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('search', searchpage, name="search"),
    path('searchUniv', search_univ, name="searchUniv"),
    path('commentDelete/<int:id>', commentDelete, name="commentDelete"),
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modelproject/blog/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from account.models import CustomUser

# Create your models here.
class Blog(models.Model):
    user = models.ForeignKey(CustomUser, null=True, on_delete=CASCADE)
    title = models.CharField(max_length=30)
    writer = models.CharField(max_length=20)
    pub_date = models.DateTimeField()
    body = models.TextField()
    image = models.ImageField(upload_to="blog/", blank = True, null = True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:30]

class Comment(models.Model):
    user = models.ForeignKey(CustomUser, null=True, on_delete=CASCADE)
    body = models.TextField()
    blog = models.ForeignKey(Blog, null=False, on_delete=CASCADE)

modelproject/blog/forms.py
from django import forms
from django.forms import fields
from .models import Blog
from .models import Comment

class BlogForm(forms.ModelForm):
    title = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={ 'class': 'title-inputs',
                                        'placeholder': 'Title'})
        )
    body = forms.CharField(
        label="",
        widget=forms.Textarea(attrs={ 'class': 'body-inputs',
                                        'placeholder': '공유하고 싶은 일상을 적어보세요.'})
        )

    class Meta:
        model = Blog
        fields = ['title', 'body', 'image']
        widgets = {
            'image': forms.FileInput(
                attrs={
                    'class':"form-control",
                    'id':"BlogformFile"
                }
            )
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

modelproject/blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.utils import timezone
from .models import Blog, Comment
from .forms import BlogForm, CommentForm
from django.core.paginator import Paginator
import math
from account.models import CustomUser
from django.db.models import F

# Create your views here.
def home (request):
    blogs = Blog.objects.order_by('-pub_date')
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    n = math.ceil(len(blogs) / 3 )
    return render(request, 'home.html', {'blogs':paginated_blogs, 'range':range(1, n+1), 'ten':range(1, 11), 'n': len(blogs)})

def detail (request, id):
    blog = Blog.objects.get(id = id)
    comments = Comment.objects.filter(blog = blog)
    new_comment = Comment()
    if request.method == 'POST':
        new_comment.body = request.POST['body']
        new_comment.blog = blog
        if request.user.is_authenticated:
            new_comment.user = request.user
        new_comment.save()
    return render(request, 'detail.html', {'blog':blog, 'comments':comments})

def new (request):
    return render(request, 'new.html')

def create(request):
    new_blog = Blog()
    new_blog.title = request.POST['title']
    new_blog.writer = request.POST['writer']
    new_blog.pub_date = timezone.now()
    new_blog.image = request.FILES['image']
    new_blog.body = request.POST['body']
    new_blog.save()
    return redirect('blog:detail', new_blog.id)

def update(request, id):
    blog = Blog.objects.get(id = id)
    if request.method == 'POST':
        blog.title = request.POST['title']
        blog.body = request.POST['body']
        blog.save()
        return redirect('blog:detail', blog.id)
    return render(request, 'update.html', {'blog':blog})

def delete(request, id):
    blog = Blog.objects.get(id = id)
    blog.delete()
    return redirect('home')

def new_with_django_form (request):
    form = BlogForm()
    if request.user.is_authenticated:
        return render(request, 'new_with_django_form.html', {'form':form})
    return redirect('account:login')

def create_with_django_form(request):
    form = BlogForm(request.POST, request.FILES) # form 데이터를 처리하기 위해서 request.POST와 request.FILES가 필요함을 의미합니다.
    if form.is_valid(): # 유효성 검사 
        new_blog = form.save(commit=False) # 임시 저장 나머지 필드(칼럼)를 채우기 위함
        new_blog.writer = request.user
        new_blog.user = request.user
        new_blog.pub_date = timezone.now()
        new_blog.save()
        return redirect('blog:detail', new_blog.id)
    return redirect('home')

def searchpage(request):
    user = request.user
    blogs = Blog.objects.filter(writer = user)
    paginator = Paginator(blogs, 3) # blogs를 3개씩 쪼갠다
    page = request.GET.get('page') # 해당 정보가 오지 않아도 넘어간다
    paginated_blogs = paginator.get_page(page)
    n = len(blogs)
    return render(request, 'search.html', {'blogs' : blogs, 'n':n})

def search_univ(request):
    univUser = request.user
    blogs = Blog.objects.select_related('user').filter(user__university = univUser.university)
    paginator = Paginator(blogs, 3)
    page = request.GET.get('page')
    paginated_blogs = paginator.get_page(page)
    n = math.ceil(len(blogs) / 3 )
    return render(request, 'searchUniv.html', {'blogs':paginated_blogs, 'range':range(1, n+1), 'ten':range(1, 11), 'n': len(blogs)})

def commentDelete(request, id):
    comment = Comment.objects.get(id=id)
    blog_id = comment.blog.id
    comment.delete()
    return redirect('blog:detail', blog_id)

modelproject/blog/templates/detail.html
{% extends 'base.html' %}
    {% block content %}
    {% load static %}
    <div>
        <img src="{% static 'img3.jpg'%}" style="position: absolute; left: 0px;
        top: 0px; z-index: -1; opacity: 0.75; width: 100%; height:450px;">
        <div class="home-welcome">
        {% if user.is_authenticated %}
        <h3 style="color: white;">{{user.location}}에 살고 {{user.university}}에 다니는 {{user.nickname}}님,<br>안녕하세요!</h3>
        {% else %}
        <h3 style="color: white;"">Blog에 오신 것을 환영합니다.</h3>
        {% endif %}
        </div>
    </div>
    <h1>📌{{blog.title}} </h1>
    <h3>🖋{{blog.writer}}</h3>
    <p>{{blog.body|linebreaks}}</p>
    {% if blog.image %}
    <p><img src="{{blog.image.url}}" alt="" style="max-width: 500px;"></p>
    {% endif %}
    {% if user.username == blog.writer %}
    <a href="{% url 'blog:update' blog.id%}" class="btn-green">Edit</a>
    <a href="{% url 'blog:delete' blog.id%}" class="btn-green">Delete</a>
    {% endif %}
    <form action="{% url 'blog:detail' blog.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>댓글 : <input type="text" name="body" class="comment-inputs"> 
            <button type="submit" class="btn-green" style="font-size: 10px;">작성하기</button>
        </p>
    </form>
    {% for comment in comments %}
    {% if comment.user != null %}
    <p>{{comment.user}} : {{comment.body}} 
        {% if comment.user == user %}
        <a href={% url 'blog:commentDelete' comment.id %}>삭제</a>
    </p>
    
    {%endif%}
    {% else %}
    <p>익명 : {{comment.body}}</p>
    {%endif%}
    {%endfor%}

    <a href="{% url 'home' %}" class= "btn-green">Home</a> 
    {%endblock%}

modelproject/blog/templates/home.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load static %}
    {% block content %}
    <div>
        <img src="{% static 'img3.jpg'%}" style="position: absolute; left: 0px;
        top: 0px; z-index: -1; opacity: 0.75; width: 100%; height:450px;">
        <div class="home-welcome">
        {% if user.is_authenticated %}
        <h3 style="color: white;">{{user.location}}에 살고 {{user.university}}에 다니는 {{user.nickname}}님,<br>안녕하세요!</h3>
        {% else %}
        <h3 style="color: white;"">Blog에 오신 것을 환영합니다.</h3>
        {% endif %}
        </div>
    </div>
    <h3 style="text-align: left; margin-top: 8px;">전체글 ({{n}})</h3>
    <a href="{% url 'blog:new' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-pencil-square" id="Newpost-icon" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg></a><br>
    {%for blog in blogs%}
    <a href="{% url 'blog:detail' blog.id %}">
    <div class="list-content">
    <h4>{{blog.title}}</h4>
    <h5>{{ blog.writer }}</h5>
    {{ blog.summary }}...<br>
    </div></a>
    {%endfor%}
    <div class="paginator">
        {% if blogs.has_previous %}
            <a href="?page=1">◀️◀️</a>
            <a href="?page={{blogs.previous_page_number}}">◀️</a>
        {% endif %}
        {% if blogs.paginator.num_pages > 10 %}
            {% for number in ten %}
                {% if blogs.pages|sub:number > 0%}
                <a href="?page={{blogs.number|sub:number}}">{{blogs.pages|sub:number}}</a>
                {% endif %}
            {% endfor %}
        {% else %}
            {% for number in range %}
            {% if number == blogs.number %}
            <a href="?page={{number}}"><span class="selected-page">{{number}}</span></a>
            {% else %}
            <a href="?page={{number}}"><span class="not-selected-page">{{number}}</span></a>
            {% endif %}
            {% endfor %}
        {%endif%}
        {% if blogs.has_next %}
        <a href="?page={{blogs.next_page_number}}">▶️</a>
        <a href="?page={{blogs.paginator.num_pages}}">▶️▶️</a>
        {% endif %}
    </div>
    {% endblock %}

modelproject/blog/templates/new.html
{% extends 'base.html' %}
    {% block content %}
    <form action="{% url 'blog:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <p>제목 :<input type="text" name="title" placeholder="Title"></p>
        <p>작성자 : <input type="text" name="writer" placeholder="Writer"></p>
        <p>사진 업로드: <input type="file" name="image"></p>
        <textarea name="body" cols="30" rows="10" placeholder="Write blog here"></textarea>
        <button type="submit">submit</button>
    </form>
    {%endblock%}

modelproject/blog/templates/new_with_django_form.html
{% extends 'base.html' %}
{% load static %}
    {% block content %}
    <div>
        <img src="{% static 'img3.jpg'%}" style="position: absolute; left: 0px;
        top: 0px; z-index: -1; opacity: 0.75; width: 100%; height:450px;">
        <div class="home-welcome">
        <h1 style="color: white;">새로운 글 쓰기✍🏻</h1>
        </div>
    </div>
<form action="{% url 'blog:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn-green">작성하기</button>
</form>
{%endblock%}

modelproject/blog/templates/search.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load static %}
    {% block content %}
    <div>
        <img src="{% static 'img3.jpg'%}" style="position: absolute; left: 0px;
        top: 0px; z-index: -1; opacity: 0.75; width: 100%; height:450px;">
        {% if user.is_authenticated %}
        <div class="home-welcome">
        <h3 style="color: white;">{{user.location}}에 살고 {{user.university}}에 다니는 {{user.nickname}}님,<br>안녕하세요!</h3>
        {% else %}
        <h3 style="color: white;"">Blog에 오신 것을 환영합니다.</h3>
        {% endif %}
        </div>
    </div>
    <h3 style="text-align: left; margin-top: 8px;">내가 쓴 글 ({{n}})</h3>
    <a href="{% url 'blog:new' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-pencil-square" id="Newpost-icon" viewBox="0 0 16 16">
        <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
        <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
      </svg></a><br>
    {%for blog in blogs%}
    <a href="{% url 'blog:detail' blog.id %}">
    <div class="list-content">
    <h4>{{blog.title}}</h4>
    <h5>{{ blog.writer }}</h5>
    {{ blog.summary }}...<br>
    </div></a>
    {%endfor%}
    <div class="paginator">
        {% if blogs.has_previous %}
            <a href="?page=1">◀️◀️</a>
            <a href="?page={{blogs.previous_page_number}}">◀️</a>
        {% endif %}
        {% if blogs.paginator.num_pages > 10 %}
            {% for number in ten %}
                {% if blogs.pages|sub:number > 0%}
                <a href="?page={{blogs.number|sub:number}}">{{blogs.pages|sub:number}}</a>
                {% endif %}
            {% endfor %}
        {% else %}
            {% for number in range %}
            {% if number == blogs.number %}
            <a href="?page={{number}}"><span class="selected-page">{{number}}</span></a>
            {% else %}
            <a href="?page={{number}}"><span class="not-selected-page">{{number}}</span></a>
            {% endif %}
            {% endfor %}
        {%endif%}
        {% if blogs.has_next %}
        <a href="?page={{blogs.next_page_number}}">▶️</a>
        <a href="?page={{blogs.paginator.num_pages}}">▶️▶️</a>
        {% endif %}
    </div>
    {% endblock %}

modelproject/blog/templates/searchUniv.html
{% extends 'base.html' %}
{% load mathfilters %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img3.jpg'%}" style="position: absolute; left: 0px;
    top: 0px; z-index: -1; opacity: 0.75; width: 100%; height:450px;">
    <div class="home-welcome">
    {% if user.is_authenticated %}
    <h3 style="color: white;">{{user.university}}에 재학 중인 학생들의 글입니다.</h3>
    {% else %}
    <h3 style="color: white;"">해당 페이지는 로그인 이후 이용하실 수 있습니다. </h3>
    {% endif %}
    </div>
</div>
<h3 style="text-align: left; margin-top: 8px;">전체글 ({{n}})</h3>
<a href="{% url 'blog:new' %}"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="black" class="bi bi-pencil-square" id="Newpost-icon" viewBox="0 0 16 16">
    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
  </svg></a><br>
    {%for blog in blogs%}
    <a href="{% url 'blog:detail' blog.id %}">
    <div class="list-content">
    <h4>{{blog.title}}</h4>
    <h5>{{ blog.writer }}</h5>
    {{ blog.summary }}...<br>
    </div></a>
    {%endfor%}
    <div class="paginator">
        {% if blogs.has_previous %}
            <a href="?page=1">◀️◀️</a>
            <a href="?page={{blogs.previous_page_number}}">◀️</a>
        {% endif %}
        {% if blogs.paginator.num_pages > 10 %}
            {% for number in ten %}
                {% if blogs.pages|sub:number > 0%}
                <a href="?page={{blogs.number|sub:number}}">{{blogs.pages|sub:number}}</a>
                {% endif %}
            {% endfor %}
        {% else %}
            {% for number in range %}
            {% if number == blogs.number %}
            <a href="?page={{number}}"><span class="selected-page">{{number}}</span></a>
            {% else %}
            <a href="?page={{number}}"><span class="not-selected-page">{{number}}</span></a>
            {% endif %}
            {% endfor %}
        {%endif%}
        {% if blogs.has_next %}
        <a href="?page={{blogs.next_page_number}}">▶️</a>
        <a href="?page={{blogs.paginator.num_pages}}">▶️▶️</a>
        {% endif %}
    </div>
    {% endblock %}

modelproject/blog/templates/update.html
{% extends 'base.html' %}
    {% block content %}
    <form action="{% url 'blog:update' blog.id%}" method="POST">
        {% csrf_token %}
        <input type="text" name="title" class="title-inputs" value="{{blog.title}}"><br><br>
        <textarea name="body" class="body-inputs" cols="30" rows="10">{{blog.body}}</textarea>
        <input type="submit" value="완료">
    </form>
    {%endblock%}