modelproject/account/urls.py
from django.urls import path
from .views import *

app_name = 'account'

urlpatterns =[
    path('signup/', signup_view, name = 'signup'),
    path('login/', login_view, name = 'login'),
    path('logout/', logout, name='logout')
]

modelproject/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('<int:id>', detail, name='detail'),
    path('new/', new_with_django_form, name='new'),
    path('create/', create_with_django_form, name='create'),
    path("update/<int:id>", update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
    path('search', searchpage, name="search"),
    path('searchUniv', search_univ, name="searchUniv"),
    path('commentDelete/<int:id>', commentDelete, name="commentDelete"),
]

modelproject/modelproject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modelproject/modelproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <style>
      #Blogform-title{
        width: 30%;
        margin-left: 35%;
      }
      #BlogformFile{
        width: 44%;
        margin-left:27%;
      }
      .home-welcome{
        width: 100%;
        height: 380px;
        text-align: center;
        padding-top:170px;
      }
      #Newpost-icon{
        position: absolute;
        top: 464px;
        left:92%;
      }
      a{
        text-decoration: none;
        color:black;
      }
      .list-content{
        text-align: left;
        padding: 24px 0 18px;
        border-bottom: 1px solid #efefef;
      }
      .paginator{
        padding: 10px 0 10px;
      }
      .selected-page{
        border-radius: 30px;
        background-color: #198754;
        color: white;
        min-width: 10px;
        height: 30px;
        margin: 0 4px;
        padding: 0 10px;
        line-height: 30px;
      }
      .not-selected-page{
        margin: 0 4px;
        padding: 0 10px;
        line-height: 30px;
      }
      .container{
        margin-bottom: 30px;
      }
      .username-input{
        border: gray;
      }
      .signup-form{
        background-color: #f8f9fa;
        padding-top: 35px;
        padding-left: 30px;
        padding-right: 20px;
        padding-bottom: 15px;
        text-align: left;
      }
      .signup-p{
        margin-left: 30%;
      }
      .signup-btn{
        margin: 0 45% 0 45%;
        color: #198754;
        border: solid #198754 2px;
        border-radius: .25rem;
        background-color: transparent;
        height: 40px;
      }
      .signup-btn:hover{
        background-color: #198754;
        color:white;
      }
      .signup-inputs{
        width: 250px;
        height: 40px;
      }
      .title-inputs{
        background-color: none;
        border: none;
        color: black;
        text-align: center;
        font-size: 3em;
      }
      .body-inputs{
        background-color: #d6d5d5;
        color: black;
        border: none;
        width: 60%;
      }
      .comment-inputs{
        margin-top: 15px;
        background-color: #FAFAFA;
        color: #B5B6BA;
        font-size: 1.1em;
        border: none;
      }
      .btn-green{
        text-align: center;
        text-decoration: none;
        vertical-align: middle;
        border: 1px solid #198754;
        background-color: transparent;
        color: #198754;
        padding: 8px 10px;
        font-size: 12px;
        border-radius: .25rem;
        font-weight: 400;
      }
      .btn-green:hover{
        color: #fff;
        background-color: #198754;
      }
      .footer{
        border-top: 1px solid #e8e8e8;
        line-height: 46px;
        color: #aaa;
        text-align: center;
      }
    </style>
    <title>BLOG</title>
    <style>
      body {
        text-align: center;
        }
    </style>
  </head>
  <body>
    {% load static %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'image_Chunsik.png'%}" alt="" style="width: 50px; height: 50px;"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:new' %} ">작성하기</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{user.nickname}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="{% url 'blog:search' %}">내가 쓴 글</a></li>
                <li><a class="dropdown-item" href="{% url 'blog:searchUniv' %}">{{user.university}}에서 쓴 글</a></li>
              </ul>
            </li>
            {% endif %}
            {% if user.is_authenticated%}
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">{{request.user}}님, 안녕하세요! </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:logout' %}" tabindex="-1" aria-disabled="true">로그아웃</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:login' %}" tabindex="-1" aria-disabled="true">로그인</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account:signup' %}" tabindex="-1" aria-disabled="true">회원가입</a>
            </li>
            {% endif %}
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class = "container">
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
      <small class="copyright">Blog is made by <a href="https://www.instagram.com/_pretty_everywhere/" style="color: cornflowerblue;">Yeonju</a></small>
    </div>
  </body>
</html>